version: '3'

volumes:
  cassandra-data:
  redis-data:

services:
  cassandra:
    image: cassandra
    deploy:
      replicas: 1
      restart_policy:
        condition: on-failure
    networks:
      - cassandra-net
    volumes:
      - cassandra-data:/var/lib/cassandra
    ports:
      - "9160:9160"
      - "7199:7199"
      - "7000:7000" 
      - "7001:7001" 
      - "9042:9042"

  redis:
    image: redis
    deploy:
      replicas: 1
      restart_policy:
        condition: on-failure
    networks:
      - cassandra-net  # Use the same network as Cassandra
    volumes:
      - redis-data:/data
    ports:
      - "6379:6379"

networks:
  cassandra-net:
    driver: bridge  # Specify the driver for the network
